project_id = "lnhbamzhturwkhcwiohr"

[functions.generate-itinerary]
verify_jwt = false

[functions.kinu-ai]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.unsplash]
verify_jwt = false

[functions.amadeus-flights]
verify_jwt = false
